# CMake generated Testfile for 
# Source directory: /home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test
# Build directory: /home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(MapValueExtractorTest.testExtractValueForIdentityMapExtractor "/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/map-helpers-test" "--run_test=MapValueExtractorTest/testExtractValueForIdentityMapExtractor" "--catch_system_error=yes")
set_tests_properties(MapValueExtractorTest.testExtractValueForIdentityMapExtractor PROPERTIES  _BACKTRACE_TRIPLES "/home/zhangjoe/Desktop/GraduateWork/hot/tests/CMakeLists.txt;21;add_test;/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/CMakeLists.txt;14;add_boost_test;/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/CMakeLists.txt;0;")
add_test(MapValueExtractorTest.testExtractValueFromPair "/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/map-helpers-test" "--run_test=MapValueExtractorTest/testExtractValueFromPair" "--catch_system_error=yes")
set_tests_properties(MapValueExtractorTest.testExtractValueFromPair PROPERTIES  _BACKTRACE_TRIPLES "/home/zhangjoe/Desktop/GraduateWork/hot/tests/CMakeLists.txt;21;add_test;/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/CMakeLists.txt;14;add_boost_test;/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/CMakeLists.txt;0;")
add_test(MapValueExtractorTest.testExtractValueFromPionterPair "/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/map-helpers-test" "--run_test=MapValueExtractorTest/testExtractValueFromPionterPair" "--catch_system_error=yes")
set_tests_properties(MapValueExtractorTest.testExtractValueFromPionterPair PROPERTIES  _BACKTRACE_TRIPLES "/home/zhangjoe/Desktop/GraduateWork/hot/tests/CMakeLists.txt;21;add_test;/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/CMakeLists.txt;14;add_boost_test;/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/CMakeLists.txt;0;")
add_test(STLLikeIndexTest.testIdentityValuesMap "/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/map-helpers-test" "--run_test=STLLikeIndexTest/testIdentityValuesMap" "--catch_system_error=yes")
set_tests_properties(STLLikeIndexTest.testIdentityValuesMap PROPERTIES  _BACKTRACE_TRIPLES "/home/zhangjoe/Desktop/GraduateWork/hot/tests/CMakeLists.txt;21;add_test;/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/CMakeLists.txt;14;add_boost_test;/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/CMakeLists.txt;0;")
add_test(STLLikeIndexTest.testPairValuesMap "/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/map-helpers-test" "--run_test=STLLikeIndexTest/testPairValuesMap" "--catch_system_error=yes")
set_tests_properties(STLLikeIndexTest.testPairValuesMap PROPERTIES  _BACKTRACE_TRIPLES "/home/zhangjoe/Desktop/GraduateWork/hot/tests/CMakeLists.txt;21;add_test;/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/CMakeLists.txt;14;add_boost_test;/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/CMakeLists.txt;0;")
add_test(STLLikeIndexTest.testUpsert "/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/map-helpers-test" "--run_test=STLLikeIndexTest/testUpsert" "--catch_system_error=yes")
set_tests_properties(STLLikeIndexTest.testUpsert PROPERTIES  _BACKTRACE_TRIPLES "/home/zhangjoe/Desktop/GraduateWork/hot/tests/CMakeLists.txt;21;add_test;/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/CMakeLists.txt;14;add_boost_test;/home/zhangjoe/Desktop/GraduateWork/hot/tests/idx/map-helpers-test/CMakeLists.txt;0;")
